version: '3'


services:
  mariadb:
    container_name: mariadb
    image: darthos/joomla_db:0.3



  php:
    container_name: joomla
    image: darthos/joomla_php:0.3
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "8081:80"




