version: '3'


services:
  mariadb:
    image: mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=bn_joomla
      - MARIADB_PASSWORD=bitnami_joomla
      - MARIADB_DATABASE=bitn_jooml
  php:
    container_name: joomla
    build:
      context: ./joomla
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "8080:80"
    restart: always
