version: '3'


services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=ead_user
      - MARIADB_PASSWORD=ead_password
      - MARIADB_DATABASE=ead_joomla

  php:
    container_name: joomla
    build:
      context: ./joomla
      dockerfile: Dockerfile_install
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "8081:80"
    volumes:
      - ./joomla/app:/app

