version: '3'


services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile

  php:
    container_name: joomla
    build:
      context: ./joomla
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "8081:80"


